Fix cli cache prune command
wp-cli/wp-cli pull request #5660
Opened 2022-07-19 15:27 UTC by bret-miller

Use version number instead of timestamp to keep the latest version of each cached package.

2022-07-20 11:03 UTC, bret-miller commented
@wojsmol Thank you. I understand better the coding style now.

2022-07-20 11:10 UTC, wojsmol commented
@bret-miller You can apply changes by merging  https://github.com/bret-miller/wp-cli/pull/1

2022-07-20 15:09 UTC, wojsmol commented
[This](https://github.com/wp-cli/wp-cli/runs/7430165029?check_suite_focus=true#step:13:145) tests failure is related to your PR.

2022-07-28 15:22 UTC, danielbachhuber reviewed
Thanks for the pull request, @bret-miller !

It's a little confusing to figure out what's going on with the diff.

Could you update your pull request description with more detail on the before and after behaviors?

Alternatively or in addition to, would it be possible to incorporate some test coverage documenting the change?

2022-07-28 15:36 UTC, bret-miller commented
Fixed description at the top.

2022-07-28 15:43 UTC, danielbachhuber commented
> Fixed description at the top.

@bret-miller Thank you! I'll test this out when I have some time in the next week or so.

2022-08-04 14:57 UTC, danielbachhuber requested changes
In looking at this a little further, I think we should change the approach slightly.

```php
public function prune( $method = 'timestamp' )
```

More specifically:
1. We'd default to 'timestamp' to avoid a breaking change on the existing behavior.
2. Your new behavior could be applied with `$method = 'version'`.

Then, we could offer a flag in `wp cli cache prune` to prune based on 'version' instead of 'timestamp'. I'm not sure if we should change the default behavior, however.

2022-08-08 12:53 UTC, bret-miller commented
@danielbachhuber, since the current approach to prune removes _nothing_ in the cache since nothing in the cache uses a timestamp anymore, at least as far as I can tell. So your solution would require people to enter another parameter beyond the "wp cli cache prune" command in order to actually prune the cache. Perhaps a modification that uses either the timestamp or a version number based on what it finds in the cache would be a solution? 

I am just trying to fix a command that is currently completely broken from a functional standpoint. I think it would be confusing for wp cli users to need to add an additional parameter to make a command work when it should just work. It broke when wp cli changed it's approach to suffix downloaded modules with a version number instead of a timestamp. Does it ever use a timestamp anymore? If not, why keep a default that renders a command ineffective?

2022-08-08 13:06 UTC, danielbachhuber commented
@bret-miller Ok, I'm amenable to changing `wp cli cache prune` to default to `--method=version`.

However, the change should be applied to `WP_CLI/FileCache` in a backwards-compatible manner.

2022-08-08 13:40 UTC, bret-miller commented
Unfortunately I don't have the time to work on this. So I am pulling back on this for now. Hopefully someone will fix it.

2022-08-08 13:40 UTC, closed without merging

2022-08-10 10:59 UTC, danielbachhuber commented
@bret-miller Sounds good! Appreciate the time you put into the pull request. It will serve as a good point of reference for whomever picks it up.