Add runtime_args to options array for runcommand
wp-cli/wp-cli pull request #5722
Opened 2023-01-10 15:49 UTC by mrsdizzie

Per https://wordpress.slack.com/archives/C02RP4T41/p1673268015148999?thread_ts=1672934225.683679&cid=C02RP4T41

I have a command that calls `WP_CLI::runcommand` a lot and I want to set some default global options for most of these (particularly `--skip-themes --skip-plugins`). I also have default global options for `WP_CLI::runcommand` itself.

Currently, this ends up looking something like:

```
private $default_cli_opts = array(
	'return'       => 'all',
	'exit_error'   => false,
);

private $default_command_opts = '--skip-themes --skip-plugins';

WP_CLI::runcommand( "config has set WPCACHEHOME --path=$path " . $this->default_command_opts, $this->default_cli_opts );
etc...
```

It would be nice to be able to keep these options in a single place like:

```
private $default_cli_opts = array(
	'return'       => 'all', // returns an OBJECT
	'exit_error'   => false,
	'runtime_args' => array( '--skip-themes', '--skip-plugins' ),
);

WP_CLI::runcommand( "config has set WPCACHEHOME --path=$path", $this->default_cli_opts );
```
This PR just appends the options to the command as if the caller included them in the command directly.

I didn't see any place that runcommand was tested as if being called from a script so I wasn't sure where/how to add a test for this as it isn't accessible when using wp-cli directly. Happy to add one though

2023-01-10 23:13 UTC, danielbachhuber reviewed
Tests should be great, thanks! `features/runcommand.feature` would be a good place for them.

2023-01-11 21:21 UTC, mrsdizzie commented
> Tests should be great, thanks! `features/runcommand.feature` would be a good place for them.

I added a test. I wasn't familiar with behat before this so any suggestions welcome.

2023-01-11 21:32 UTC, mrsdizzie commented
While working on this I was thinking another helpful feature might be to include the full command run as part of the object returned here:

https://github.com/wp-cli/wp-cli/blob/187eda2ffb035de86e2770983806ba240ab323e6/php/class-wp-cli.php#L1402-L1405

So there would be a way to see what this was:

https://github.com/wp-cli/wp-cli/blob/187eda2ffb035de86e2770983806ba240ab323e6/php/class-wp-cli.php#L1335

Right now I don't think there is a way to see the full command that is run?

2023-01-17 07:20 UTC, schlessera requested changes
I'm not very fond of the name `runtime_args`. This would imply we need to distinguish them from compile-time arguments, which we don't have. Everything that happens here is runtime anyway.

How about `command_args` to distinguish them from the method arguments?

2023-01-18 04:43 UTC, mrsdizzie commented
> I'm not very fond of the name `runtime_args`. This would imply we need to distinguish them from compile-time arguments, which we don't have. Everything that happens here is runtime anyway.
> 
> How about `command_args` to distinguish them from the method arguments?

Sounds good, updated!

2023-01-18 13:44 UTC, schlessera requested changes
Minor cosmetic changes.

2023-01-18 13:44 UTC, schlessera commented on php/class-wp-cli.php
> +	 *   'command_args' => array('--skip-themes'), // Additional command arguments to be used with $command
Alignment is off here.
```suggestion
	 *   'return'       => true,                // Return 'STDOUT'; use 'all' for full object.
	 *   'parse'        => 'json',              // Parse captured STDOUT to JSON array.
	 *   'launch'       => false,               // Reuse the current process.
	 *   'exit_error'   => true,                // Halt script execution on error.
	 *   'command_args' => [ '--skip-themes' ], // Additional arguments to be passed to the $command.
```

2023-01-18 13:44 UTC, schlessera commented on php/class-wp-cli.php
> +	 * * Include additional runtime arguments to be used with command.
```suggestion
	 * * Include additional arguments that are passed to the command.
```

2023-01-18 13:44 UTC, schlessera commented on php/class-wp-cli.php
> +			'command_args' => array(), //Include optional command arguments
```suggestion
		$defaults     = [
			'launch'       => true,  // Launch a new process, or reuse the existing.
			'exit_error'   => true,  // Exit on error by default.
			'return'       => false, // Capture and return output, or render in realtime.
			'parse'        => false, // Parse returned output as a particular format.
			'command_args' => [],    // Include optional command arguments.
```

2023-01-18 13:45 UTC, schlessera approved these changes

2023-01-18 14:00 UTC, merged

2023-01-18 14:00 UTC, schlessera commented
Thanks for the PR, @mrsdizzie !